// Package core provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package core

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for NewPromptFormat.
const (
	NewPromptFormatJson     NewPromptFormat = "json"
	NewPromptFormatMarkdown NewPromptFormat = "markdown"
	NewPromptFormatText     NewPromptFormat = "text"
)

// Defines values for PromptFormat.
const (
	PromptFormatJson     PromptFormat = "json"
	PromptFormatMarkdown PromptFormat = "markdown"
	PromptFormatText     PromptFormat = "text"
)

// BasicEntity defines model for BasicEntity.
type BasicEntity struct {
	Icon *string            `json:"icon,omitempty"`
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// ErrorSchema defines model for ErrorSchema.
type ErrorSchema struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// NewPrompt defines model for NewPrompt.
type NewPrompt struct {
	Content string `json:"content"`

	// Format Output format of the prompt execution
	Format NewPromptFormat `json:"format"`

	// FormatInstructions Instructions for the LLM on how to format the output
	FormatInstructions string   `json:"formatInstructions"`
	Name               string   `json:"name"`
	Parameters         []string `json:"parameters"`

	// SampleParameters Example parameter values for the prompt
	SampleParameters *map[string]string `json:"sampleParameters,omitempty"`
	Tags             []string           `json:"tags"`
}

// NewPromptFormat Output format of the prompt execution
type NewPromptFormat string

// Prompt defines model for Prompt.
type Prompt struct {
	Content string `json:"content"`

	// Format Output format of the prompt execution
	Format PromptFormat `json:"format"`

	// FormatInstructions Instructions for the LLM on how to format the output
	FormatInstructions string             `json:"formatInstructions"`
	Id                 openapi_types.UUID `json:"id"`
	Name               string             `json:"name"`
	Parameters         []string           `json:"parameters"`

	// SampleParameters Example parameter values for the prompt
	SampleParameters *map[string]string `json:"sampleParameters,omitempty"`
	Tags             []string           `json:"tags"`
}

// PromptFormat Output format of the prompt execution
type PromptFormat string

// PromptResponse defines model for PromptResponse.
type PromptResponse struct {
	Result string `json:"result"`
}

// InternalServerError defines model for InternalServerError.
type InternalServerError struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}
