// Package core provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package core

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ListPromptsParamsOrder.
const (
	Asc  ListPromptsParamsOrder = "asc"
	Desc ListPromptsParamsOrder = "desc"
)

// Defines values for AddPromptJSONBodyFormat.
const (
	AddPromptJSONBodyFormatJson     AddPromptJSONBodyFormat = "json"
	AddPromptJSONBodyFormatMarkdown AddPromptJSONBodyFormat = "markdown"
	AddPromptJSONBodyFormatText     AddPromptJSONBodyFormat = "text"
)

// Defines values for ExecutePromptParamsProvider.
const (
	ANTHROPIC ExecutePromptParamsProvider = "ANTHROPIC"
	GOOGLEAI  ExecutePromptParamsProvider = "GOOGLEAI"
	MISTRAL   ExecutePromptParamsProvider = "MISTRAL"
	OLLAMA    ExecutePromptParamsProvider = "OLLAMA"
	OPENAI    ExecutePromptParamsProvider = "OPENAI"
)

// Defines values for ExecutePromptJSONBodyFormat.
const (
	ExecutePromptJSONBodyFormatJson     ExecutePromptJSONBodyFormat = "json"
	ExecutePromptJSONBodyFormatMarkdown ExecutePromptJSONBodyFormat = "markdown"
	ExecutePromptJSONBodyFormatText     ExecutePromptJSONBodyFormat = "text"
)

// Defines values for UpdatePromptJSONBodyFormat.
const (
	Json     UpdatePromptJSONBodyFormat = "json"
	Markdown UpdatePromptJSONBodyFormat = "markdown"
	Text     UpdatePromptJSONBodyFormat = "text"
)

// ListPromptsParams defines parameters for ListPrompts.
type ListPromptsParams struct {
	// Page page number
	Page *int32 `form:"page,omitempty" json:"page,omitempty"`

	// PageSize maximum number of results to return
	PageSize *int32 `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// SortBy field to sort by
	SortBy *string `form:"sortBy,omitempty" json:"sortBy,omitempty"`

	// Order sort order
	Order *ListPromptsParamsOrder `form:"order,omitempty" json:"order,omitempty"`

	// Tags tags to filter by
	Tags *[]string `form:"tags,omitempty" json:"tags,omitempty"`

	// Q starts with
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Detail basic or full
	Detail *string `form:"detail,omitempty" json:"detail,omitempty"`
}

// ListPromptsParamsOrder defines parameters for ListPrompts.
type ListPromptsParamsOrder string

// AddPromptJSONBody defines parameters for AddPrompt.
type AddPromptJSONBody struct {
	Content string `json:"content"`

	// Format Output format of the prompt execution
	Format AddPromptJSONBodyFormat `json:"format"`

	// FormatInstructions Instructions for the LLM on how to format the output
	FormatInstructions string   `json:"formatInstructions"`
	Name               string   `json:"name"`
	Parameters         []string `json:"parameters"`

	// SampleParameters Example parameter values for the prompt
	SampleParameters *map[string]string `json:"sampleParameters,omitempty"`
	Tags             []string           `json:"tags"`
}

// AddPromptJSONBodyFormat defines parameters for AddPrompt.
type AddPromptJSONBodyFormat string

// ExecutePromptJSONBody defines parameters for ExecutePrompt.
type ExecutePromptJSONBody struct {
	// Content Override the prompt with a custom prompt. Used for tests.
	Content *string `json:"content,omitempty"`

	// Format Override the output format. Used for tests.
	Format *ExecutePromptJSONBodyFormat `json:"format,omitempty"`

	// FormatInstructions Override the format instructions with custom instructions. Used for tests.
	FormatInstructions *string `json:"formatInstructions,omitempty"`

	// Parameters Override the parameters with a custom list of parameters. Used for tests.
	Parameters       *[]string          `json:"parameters,omitempty"`
	ParametersValues *map[string]string `json:"parametersValues,omitempty"`
}

// ExecutePromptParams defines parameters for ExecutePrompt.
type ExecutePromptParams struct {
	// Id ID of prompt to execute
	Id *openapi_types.UUID `form:"id,omitempty" json:"id,omitempty"`

	// Name Name of prompt to execute
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Provider LLM Provider
	Provider *ExecutePromptParamsProvider `form:"provider,omitempty" json:"provider,omitempty"`

	// Llm LLM to use for execution
	Llm *string `form:"llm,omitempty" json:"llm,omitempty"`

	// MaxTokens Maximum number of tokens to generate
	MaxTokens *int32 `form:"maxTokens,omitempty" json:"maxTokens,omitempty"`

	// Temperature Temperature for LLM generation (0.0-1.0)
	Temperature *float32 `form:"temperature,omitempty" json:"temperature,omitempty"`
}

// ExecutePromptParamsProvider defines parameters for ExecutePrompt.
type ExecutePromptParamsProvider string

// ExecutePromptJSONBodyFormat defines parameters for ExecutePrompt.
type ExecutePromptJSONBodyFormat string

// FormatPromptJSONBody defines parameters for FormatPrompt.
type FormatPromptJSONBody struct {
	Parameters *map[string]string `json:"parameters,omitempty"`
}

// FormatPromptParams defines parameters for FormatPrompt.
type FormatPromptParams struct {
	// Id ID of prompt to execute
	Id *openapi_types.UUID `form:"id,omitempty" json:"id,omitempty"`

	// Name Name of prompt to execute
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// UpdatePromptJSONBody defines parameters for UpdatePrompt.
type UpdatePromptJSONBody struct {
	Content string `json:"content"`

	// Format Output format of the prompt execution
	Format UpdatePromptJSONBodyFormat `json:"format"`

	// FormatInstructions Instructions for the LLM on how to format the output
	FormatInstructions string             `json:"formatInstructions"`
	Id                 openapi_types.UUID `json:"id"`
	Name               string             `json:"name"`
	Parameters         []string           `json:"parameters"`

	// SampleParameters Example parameter values for the prompt
	SampleParameters *map[string]string `json:"sampleParameters,omitempty"`
	Tags             []string           `json:"tags"`
}

// UpdatePromptJSONBodyFormat defines parameters for UpdatePrompt.
type UpdatePromptJSONBodyFormat string

// AddPromptJSONRequestBody defines body for AddPrompt for application/json ContentType.
type AddPromptJSONRequestBody AddPromptJSONBody

// ExecutePromptJSONRequestBody defines body for ExecutePrompt for application/json ContentType.
type ExecutePromptJSONRequestBody ExecutePromptJSONBody

// FormatPromptJSONRequestBody defines body for FormatPrompt for application/json ContentType.
type FormatPromptJSONRequestBody FormatPromptJSONBody

// UpdatePromptJSONRequestBody defines body for UpdatePrompt for application/json ContentType.
type UpdatePromptJSONRequestBody UpdatePromptJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/v1/prompts)
	ListPrompts(c *gin.Context, params ListPromptsParams)

	// (POST /api/v1/prompts)
	AddPrompt(c *gin.Context)

	// (POST /api/v1/prompts/execute)
	ExecutePrompt(c *gin.Context, params ExecutePromptParams)

	// (POST /api/v1/prompts/format)
	FormatPrompt(c *gin.Context, params FormatPromptParams)

	// (DELETE /api/v1/prompts/{id})
	DeletePrompt(c *gin.Context, id openapi_types.UUID)

	// (GET /api/v1/prompts/{id})
	GetPromptByID(c *gin.Context, id openapi_types.UUID)

	// (PUT /api/v1/prompts/{id})
	UpdatePrompt(c *gin.Context, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListPrompts operation middleware
func (siw *ServerInterfaceWrapper) ListPrompts(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPromptsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sortBy" -------------

	err = runtime.BindQueryParameter("form", true, false, "sortBy", c.Request.URL.Query(), &params.SortBy)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sortBy: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", c.Request.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter order: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "tags" -------------

	err = runtime.BindQueryParameter("form", false, false, "tags", c.Request.URL.Query(), &params.Tags)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tags: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "detail" -------------

	err = runtime.BindQueryParameter("form", true, false, "detail", c.Request.URL.Query(), &params.Detail)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter detail: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPrompts(c, params)
}

// AddPrompt operation middleware
func (siw *ServerInterfaceWrapper) AddPrompt(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddPrompt(c)
}

// ExecutePrompt operation middleware
func (siw *ServerInterfaceWrapper) ExecutePrompt(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ExecutePromptParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", c.Request.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", c.Request.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "provider" -------------

	err = runtime.BindQueryParameter("form", true, false, "provider", c.Request.URL.Query(), &params.Provider)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter provider: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "llm" -------------

	err = runtime.BindQueryParameter("form", true, false, "llm", c.Request.URL.Query(), &params.Llm)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter llm: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "maxTokens" -------------

	err = runtime.BindQueryParameter("form", true, false, "maxTokens", c.Request.URL.Query(), &params.MaxTokens)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter maxTokens: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "temperature" -------------

	err = runtime.BindQueryParameter("form", true, false, "temperature", c.Request.URL.Query(), &params.Temperature)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter temperature: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExecutePrompt(c, params)
}

// FormatPrompt operation middleware
func (siw *ServerInterfaceWrapper) FormatPrompt(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params FormatPromptParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", c.Request.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", c.Request.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.FormatPrompt(c, params)
}

// DeletePrompt operation middleware
func (siw *ServerInterfaceWrapper) DeletePrompt(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeletePrompt(c, id)
}

// GetPromptByID operation middleware
func (siw *ServerInterfaceWrapper) GetPromptByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPromptByID(c, id)
}

// UpdatePrompt operation middleware
func (siw *ServerInterfaceWrapper) UpdatePrompt(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdatePrompt(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/prompts", wrapper.ListPrompts)
	router.POST(options.BaseURL+"/api/v1/prompts", wrapper.AddPrompt)
	router.POST(options.BaseURL+"/api/v1/prompts/execute", wrapper.ExecutePrompt)
	router.POST(options.BaseURL+"/api/v1/prompts/format", wrapper.FormatPrompt)
	router.DELETE(options.BaseURL+"/api/v1/prompts/:id", wrapper.DeletePrompt)
	router.GET(options.BaseURL+"/api/v1/prompts/:id", wrapper.GetPromptByID)
	router.PUT(options.BaseURL+"/api/v1/prompts/:id", wrapper.UpdatePrompt)
}
